### ISSUE TITLE
Would like to run robotpy simulator on raspberry-pi, but neither I, nor pip can find an appropriate .whl for robotpy-halsim-gui

### ISSUE THREAD

**Issue by mcolinj** [robotpy/robotpy-halsim-gui#9]
I'm wondering if there is something inherently preventing this (like x86 assembly in the core of some critical element), or other necessary software component that won't ever build for ARM.  If not, I'd be willing to try to take this on.    I'd need a few breadcrumbs to get started, I think.

thanks,

matthew jones
Software Mentor, FRC1076

**Comment by TheTripleV** [comment]
WPILib only builds halsim_gui for (x32/x64) bit Windows, x64 macOS, and x64 Linux.

**Comment by virtuald** [comment]
RobotPy builds on top of the distributed binary artifacts from WPILib (for this package, see https://frcmaven.wpi.edu/ui/native/release/edu/wpi/first/halsim/halsim_gui/2022.1.1).

I don't believe WPILib builds this package for ARM, so we can't either. You would need them to build it.

**Comment by virtuald** [comment]
Closing since there's nothing we can do here.
